name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./slidev

      - name: Build slides
        run: npm run build:base
        working-directory: ./slidev

      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: ./slidev/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}